project:
  type: book
  output-dir: docs

book:
  title: "Social Statistics I (Exercises)"
  author: "andrés castro araújo"
  date: last-modified
  chapters:
    - index.qmd
    - part: sec1.qmd
      chapters: 
        - week1.qmd
        - week2.qmd
    - part: sec2.qmd
      chapters: 
        - week3.qmd
        - week4.qmd
    - references.qmd

bibliography: references.bib
csl: american-journal-of-sociology.csl

format:
  html:
    theme: cosmo
    #monofont: Fira Code
    fontsize: 1em
    code-fold: show
    code-line-numbers: true
    code-tools: true
    fig-align: "center"
    mainfont: Optima
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://www.cssfontstack.com/Optima" type="text/css"/>
    
execute:
  freeze: auto

editor: visual

