<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Social Statistics I (Exercises) - 10&nbsp; Week 10</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./sec-solutions.html" rel="next">
<link href="./week09.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link rel="stylesheet" media="screen" href="https://www.cssfontstack.com/Optima" type="text/css">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./sec3.html">Models</a></li><li class="breadcrumb-item"><a href="./week10.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Week 10</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Social Statistics I (Exercises)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./sec1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computing preliminaries</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Week 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Week 2</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./sec2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data, sampling, and probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Week 3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Week 4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Week 5</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Week 6</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Week 7</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./sec3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Week 8</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Week 9</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week10.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Week 10</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./sec-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Solutions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Solutions 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Solutions 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Solutions 3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Solutions 4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Solutions 5</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Solutions 6</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Solutions 7</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Solutions 8</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#model-estimation" id="toc-model-estimation" class="nav-link active" data-scroll-target="#model-estimation"><span class="header-section-number">10.1</span> Model Estimation</a>
  <ul class="collapse">
  <li><a href="#grid-search" id="toc-grid-search" class="nav-link" data-scroll-target="#grid-search"><span class="header-section-number">10.1.1</span> Grid Search</a></li>
  <li><a href="#the-easy-way" id="toc-the-easy-way" class="nav-link" data-scroll-target="#the-easy-way"><span class="header-section-number">10.1.2</span> The Easy Way</a></li>
  <li><a href="#looking-under-the-hood" id="toc-looking-under-the-hood" class="nav-link" data-scroll-target="#looking-under-the-hood"><span class="header-section-number">10.1.3</span> Looking Under the Hood</a></li>
  </ul></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison"><span class="header-section-number">10.2</span> Model Comparison</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">10.3</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#exercise" id="toc-exercise" class="nav-link" data-scroll-target="#exercise"><span class="header-section-number">10.3.1</span> Exercise</a></li>
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1"><span class="header-section-number">10.3.2</span> Exercise</a></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2"><span class="header-section-number">10.3.3</span> Exercise</a></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3"><span class="header-section-number">10.3.4</span> Exercise</a></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4"><span class="header-section-number">10.3.5</span> Exercise</a></li>
  <li><a href="#extra" id="toc-extra" class="nav-link" data-scroll-target="#extra"><span class="header-section-number">10.3.6</span> Extra</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Week 10</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="model-estimation" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="model-estimation"><span class="header-section-number">10.1</span> Model Estimation</h2>
<p>I’m going to show you how to estimate the same model in slightly different ways.</p>
<p>Let’s take four variables from the 2018 GSS:</p>
<ul>
<li><p><code>cappun</code>: favor or oppose death penalty for murder.</p></li>
<li><p><code>polviews</code>: self-identification in a 7-point scale: extremely liberal (<code>1</code>), liberal (<code>2</code>), slightly liberal (<code>3</code>), moderate (<code>4</code>), slightly conservative (<code>5</code>), conservative (<code>6</code>), and extremely conservative (<code>7</code>).</p></li>
<li><p><code>attend</code>: how often the respondent attends religious ceremonies: never (<code>0</code>), less than once a year (<code>1</code>), about once or twice a year (<code>2</code>), several times a year (<code>3</code>), about once a month (<code>4</code>), 2-3 times a month (<code>5</code>), nearly every week (<code>6</code>), every week (<code>7</code>), and several times a week (<code>8</code>).</p></li>
<li><p><code>degree</code>: respondent’s highest degree. We will keep this variable as a <em>factor</em> variable—i.e., a kind of character vector which can be <em>ordered</em> and that plays well with R’s <em>model formula</em> syntax.</p></li>
</ul>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">theme_set</span>(<span class="fu">theme_light</span>(<span class="at">base_family =</span> <span class="st">"Optima"</span>))</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-6"><a href="#cb1-6"></a></span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="fu">library</span>(gssr)</span>
<span id="cb1-8"><a href="#cb1-8"></a>gss18 <span class="ot">&lt;-</span> <span class="fu">gss_get_yr</span>(<span class="dv">2018</span>) </span>
<span id="cb1-9"><a href="#cb1-9"></a></span>
<span id="cb1-10"><a href="#cb1-10"></a>d <span class="ot">&lt;-</span> gss18 <span class="sc">|&gt;</span> </span>
<span id="cb1-11"><a href="#cb1-11"></a>  <span class="fu">select</span>(attend, polviews, cappun, degree) <span class="sc">|&gt;</span> </span>
<span id="cb1-12"><a href="#cb1-12"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1-13"><a href="#cb1-13"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">!</span>degree, haven<span class="sc">::</span>zap_labels)) <span class="sc">|&gt;</span> </span>
<span id="cb1-14"><a href="#cb1-14"></a>  <span class="fu">mutate</span>(<span class="at">degree =</span> haven<span class="sc">::</span><span class="fu">as_factor</span>(degree)) <span class="sc">|&gt;</span> </span>
<span id="cb1-15"><a href="#cb1-15"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-16"><a href="#cb1-16"></a>    <span class="at">weekly =</span> <span class="fu">if_else</span>(attend <span class="sc">&gt;=</span> <span class="dv">7</span>, 1L, 0L),</span>
<span id="cb1-17"><a href="#cb1-17"></a>    <span class="at">polviews =</span> polviews <span class="sc">-</span> <span class="dv">4</span>,</span>
<span id="cb1-18"><a href="#cb1-18"></a>    <span class="at">cappun =</span> <span class="fu">if_else</span>(cappun <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb1-19"><a href="#cb1-19"></a>    ) <span class="sc">|&gt;</span> </span>
<span id="cb1-20"><a href="#cb1-20"></a>  <span class="fu">mutate</span>(<span class="at">conservative =</span> <span class="fu">as.integer</span>(polviews <span class="sc">&gt;</span> <span class="dv">0</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb1-21"><a href="#cb1-21"></a>  <span class="fu">drop_na</span>() </span>
<span id="cb1-22"><a href="#cb1-22"></a></span>
<span id="cb1-23"><a href="#cb1-23"></a>d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,102 × 6
   attend polviews cappun degree                   weekly conservative
    &lt;dbl&gt;    &lt;dbl&gt;  &lt;int&gt; &lt;fct&gt;                     &lt;int&gt;        &lt;int&gt;
 1      5        2      1 associate/junior college      0            1
 2      2        1      1 bachelor's                    0            1
 3      6        0      0 bachelor's                    0            0
 4      8        3      0 graduate                      1            1
 5      4       -1      1 bachelor's                    0            0
 6      7        0      1 high school                   1            0
 7      7        1      1 high school                   1            1
 8      0        0      1 less than high school         0            0
 9      4        2      1 graduate                      0            1
10      5        0      1 high school                   0            0
# ℹ 2,092 more rows</code></pre>
</div>
</div>
<p>Note that in the previous code we created two additional variables and <em>transformed</em> <code>polviews</code>:</p>
<ul>
<li><p><code>weekly</code>: attends religious ceremonies one or more times a week</p></li>
<li><p><code>polviews</code>: this variable is now centered at 0.</p></li>
<li><p><code>conservative</code>: slightly conservative, conservative, and extremely conservative.</p></li>
</ul>
<p>Last week we learned that we could estimate a “saturated model” by hand by looking at the conditional probabilities in a <span class="math inline">\(2 \times 2 \times 2\)</span> contingency table. This week, we learned how to estimated a “restricted model” like the one in <a href="#eq-restricted">Equation&nbsp;<span>10.1</span></a>. This time, however, we can’t calculate the parameters in the model by hand.</p>
<p><span id="eq-restricted"><span class="math display">\[
\log \Bigg( \frac{\Pr(\texttt{cappun}_i = 1)}{1-\Pr(\texttt{cappun}_i = 1)} \Bigg) = \alpha + \beta_1 \times \texttt{conservative}_i + \beta_2 \times \texttt{weekly}_i
\tag{10.1}\]</span></span></p>
<p>Here, we want to choose the parameters <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\beta_2\)</span> that maximize the <em>joint probability</em> of the observed data. Strictly speaking, we want choose the parameters that maximize the following expression:</p>
<p><span id="eq-logLik"><span class="math display">\[
\text{log-likelihood} = \texttt{sum(dbinom(} \boldsymbol{y} \texttt{, size = 1, prob = } \boldsymbol {\theta} \texttt{, log = TRUE))}
\tag{10.2}\]</span></span></p>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>We usually refer to this expression like this as a “probability” when the parameter <span class="math inline">\(\theta\)</span> is fixed and we are interested in making inferences about <em>unknown observations</em>; we refer to it as a “likelihood” when the data <span class="math inline">\(y\)</span> is fixed and we are interested in making inferences about <em>unknown parameters</em>.</p>
</div>
</div>
</div>
<p>Note that both <span class="math inline">\(\boldsymbol y\)</span> and <span class="math inline">\(\theta\)</span> are vectors of size 2102 (the number of observations in the data frame). Each individual <span class="math inline">\(\theta_i\)</span> is modeled as a function of our <em>predictors,</em> which are linear in the “logit” scale.</p>
<p><span class="math display">\[
\text{logit}(\theta_i) = \alpha + \beta_1 \times \texttt{conservative}_i + \beta_2 \times \texttt{weekly}_i
\]</span></p>
<p>How, then, do we estimate the parameters in our restricted model?</p>
<section id="grid-search" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="grid-search"><span class="header-section-number">10.1.1</span> Grid Search</h3>
<p>Conceptually, the easiest way to estimate these parameters is by doing what’s called a “grid search.” This is also the <em>most inefficient</em> way to do it from a computational point of view.</p>
<p>We can create a “grid” like this:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="at">alpha =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.02</span>), </span>
<span id="cb3-3"><a href="#cb3-3"></a>  <span class="at">beta1 =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.02</span>),</span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="at">beta2 =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.02</span>)</span>
<span id="cb3-5"><a href="#cb3-5"></a>)</span>
<span id="cb3-6"><a href="#cb3-6"></a></span>
<span id="cb3-7"><a href="#cb3-7"></a>grid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,030,301 × 3
   alpha beta1 beta2
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1    -1    -1 -1   
 2    -1    -1 -0.98
 3    -1    -1 -0.96
 4    -1    -1 -0.94
 5    -1    -1 -0.92
 6    -1    -1 -0.9 
 7    -1    -1 -0.88
 8    -1    -1 -0.86
 9    -1    -1 -0.84
10    -1    -1 -0.82
# ℹ 1,030,291 more rows</code></pre>
</div>
</div>
<p>We will calculate the sum of log-likelihoods ( <span class="math inline">\(ll\)</span> ) for each row in this grid, and then choose the combination that produces the maximum value in <a href="#eq-logLik">Equation&nbsp;<span>10.2</span></a>.</p>
<p><span class="math display">\[
\underset{\alpha, \beta_1, \beta_2}{\arg \max} \ \texttt{log-likelihood}
\]</span></p>
<p>To do so I will rely on this custom function (which you’ll never see again):</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>log_likelihood_cappun <span class="ot">&lt;-</span> <span class="cf">function</span>(alpha, beta1, beta2) {</span>
<span id="cb5-2"><a href="#cb5-2"></a>  </span>
<span id="cb5-3"><a href="#cb5-3"></a>  <span class="do">## the linear part of the model</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>  <span class="do">## make sure that `d` exists in the global environment!</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>  linpred <span class="ot">&lt;-</span> alpha <span class="sc">+</span> beta1 <span class="sc">*</span> d<span class="sc">$</span>conservative <span class="sc">+</span> beta2 <span class="sc">*</span> d<span class="sc">$</span>weekly</span>
<span id="cb5-6"><a href="#cb5-6"></a>  </span>
<span id="cb5-7"><a href="#cb5-7"></a>  <span class="do">## the inverse-logit transformation</span></span>
<span id="cb5-8"><a href="#cb5-8"></a>  theta <span class="ot">&lt;-</span> <span class="fu">exp</span>(linpred) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(linpred))</span>
<span id="cb5-9"><a href="#cb5-9"></a>  </span>
<span id="cb5-10"><a href="#cb5-10"></a>  <span class="do">## the sum of the log-likelihoods;</span></span>
<span id="cb5-11"><a href="#cb5-11"></a>  <span class="do">## we ultimately want coefficients that maximize this value</span></span>
<span id="cb5-12"><a href="#cb5-12"></a>  <span class="fu">return</span>(<span class="fu">sum</span>(<span class="fu">dbinom</span>(d<span class="sc">$</span>cappun, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> theta, <span class="at">log =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb5-13"><a href="#cb5-13"></a>  </span>
<span id="cb5-14"><a href="#cb5-14"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we apply the function to each row of the grid. There are more than a million rows, so it might take a few minutes!</p>
<div class="cell" data-hash="week10_cache/html/unnamed-chunk-4_ff70164ec4a51171c3adae24d442f3fc">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>out <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"double"</span>, <span class="fu">nrow</span>(grid)) <span class="do">## create empty vector</span></span>
<span id="cb6-2"><a href="#cb6-2"></a></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(out)) {  <span class="do">## this will be a slow process!!</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>  out[[i]] <span class="ot">&lt;-</span> <span class="fu">log_likelihood_cappun</span>(grid<span class="sc">$</span>alpha[[i]], grid<span class="sc">$</span>beta1[[i]], grid<span class="sc">$</span>beta2[[i]])</span>
<span id="cb6-5"><a href="#cb6-5"></a>}</span>
<span id="cb6-6"><a href="#cb6-6"></a></span>
<span id="cb6-7"><a href="#cb6-7"></a>grid<span class="sc">$</span>ll <span class="ot">&lt;-</span> out</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Finally, we search for the maximum value of <code>ll</code> using the <code>filter()</code> function from the dplyr package.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>grid <span class="sc">|&gt;</span> <span class="fu">filter</span>(ll <span class="sc">==</span> <span class="fu">max</span>(ll))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  alpha beta1 beta2     ll
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1  0.36  0.86 -0.38 -1346.</code></pre>
</div>
</div>
<p>Hopefully you can see why this form of estimation looks a little bit like mountain climbing.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>grid <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2"></a>  <span class="fu">filter</span>(<span class="fu">near</span>(alpha, <span class="fl">0.36</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(beta1, beta2)) <span class="sc">+</span> </span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="fu">geom_tile</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ll)) <span class="sc">+</span> </span>
<span id="cb9-5"><a href="#cb9-5"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> <span class="fu">filter</span>(grid, ll <span class="sc">==</span> <span class="fu">max</span>(ll)), <span class="at">size =</span> <span class="dv">4</span>, <span class="at">pch =</span> <span class="dv">13</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6"></a>  <span class="fu">geom_contour</span>(<span class="fu">aes</span>(<span class="at">z =</span> ll), <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> </span>
<span id="cb9-7"><a href="#cb9-7"></a>  <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-9"><a href="#cb9-9"></a>    <span class="at">title =</span> <span class="st">"Mountain Climbing"</span>, </span>
<span id="cb9-10"><a href="#cb9-10"></a>    <span class="at">fill =</span> <span class="st">"log-likelihood"</span>,</span>
<span id="cb9-11"><a href="#cb9-11"></a>    <span class="at">x =</span> latex2exp<span class="sc">::</span><span class="fu">TeX</span>(<span class="st">"$</span><span class="sc">\\</span><span class="st">beta_1$"</span>), </span>
<span id="cb9-12"><a href="#cb9-12"></a>    <span class="at">y =</span> latex2exp<span class="sc">::</span><span class="fu">TeX</span>(<span class="st">"$</span><span class="sc">\\</span><span class="st">beta_2$"</span>)</span>
<span id="cb9-13"><a href="#cb9-13"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="week10_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Note. Unlike what we did last week, there’s no way to calculate these parameter values by hand.</em></p>
</section>
<section id="the-easy-way" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="the-easy-way"><span class="header-section-number">10.1.2</span> The Easy Way</h3>
<p>The easiest way to estimate this model is with R’s built-in <code>glm</code> function. This stands for <em>generalized linear regression</em>. The word “generalized” should serve as foreshadowing. <em>Everything we learn here can be extended to the modeling other types of outcome variables (not just binary).</em></p>
<p>To use it we do three things:</p>
<ol type="1">
<li>Specify a <em>model formula</em> with a tilde ( <code>~</code> ) separating the outcome variable (left-hand side) from the predictors (right-hand side).</li>
<li>Specify the <code>data</code> argument. An error will show up if the variables you specified in the formula don’t exist in the data.</li>
<li>Specify the <code>family</code> argument. For a logistic regression this will always be “binomial.”</li>
</ol>
<p>Let’s save the resulting object as <code>mod</code>:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb10-2"><a href="#cb10-2"></a>mod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = cappun ~ conservative + weekly, family = "binomial", 
    data = d)

Coefficients:
 (Intercept)  conservative        weekly  
      0.3583        0.8640       -0.3741  

Degrees of Freedom: 2101 Total (i.e. Null);  2099 Residual
Null Deviance:      2767 
Residual Deviance: 2692     AIC: 2698</code></pre>
</div>
</div>
<p>You can see a lot of useful information here, including the Deviance, the Null Deviance, and the AIC.</p>
<p>As a reminder:</p>
<ul>
<li><p>The AIC is the <em>deviance</em> plus twice the number of parameters:</p>
<p><span class="math display">\[
\text{AIC} = D + 2k
\]</span></p>
<p>So 2692 + 6.</p></li>
<li><p>The <em>deviance</em> is just the log-likelihood multiplied by -2.</p>
<p>You can look at the log-likelihood by using the <code>logLik()</code> function. It should roughly correspond to the <code>ll</code> value we calculated earlier doing the grid search.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">logLik</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -1346.112 (df=3)</code></pre>
</div>
</div></li>
<li><p>The <em>null deviance</em> corresponds to a model with no predictors.</p>
<p><em>You should be able to calculate this very easily! It’s going back to univariate statistics!</em></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>nullll <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">dbinom</span>(d<span class="sc">$</span>cappun, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fu">mean</span>(d<span class="sc">$</span>cappun), <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb14-2"><a href="#cb14-2"></a>nullll <span class="sc">*</span> <span class="sc">-</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2767.318</code></pre>
</div>
</div></li>
</ul>
<p>Sometimes you’ll see people use the <code>summary()</code> function to get even <em>more</em> information.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cappun ~ conservative + weekly, family = "binomial", 
    data = d)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.35834    0.05748   6.234 4.56e-10 ***
conservative  0.86396    0.10519   8.214  &lt; 2e-16 ***
weekly       -0.37415    0.11225  -3.333 0.000858 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2767.3  on 2101  degrees of freedom
Residual deviance: 2692.2  on 2099  degrees of freedom
AIC: 2698.2

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Or you’ll see people using the <code>coef()</code>—or <code>coefficients()</code>—functions to extract the parameter values.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">coef</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) conservative       weekly 
   0.3583377    0.8639560   -0.3741454 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">coefficients</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) conservative       weekly 
   0.3583377    0.8639560   -0.3741454 </code></pre>
</div>
</div>
<p>There are also some useful packages that work seamlessly with <code>glm</code>.</p>
<hr>
<p>The <a href="https://broom.tidymodels.org/">broom</a> package, with it’s associated three functions.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term         estimate std.error statistic  p.value
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)     0.358    0.0575      6.23 4.56e-10
2 conservative    0.864    0.105       8.21 2.15e-16
3 weekly         -0.374    0.112      -3.33 8.58e- 4</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1         2767.    2101 -1346. 2698. 2715.    2692.        2099  2102</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="do">## the .fitted values are predictions in log-odds</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="do">## add type.predict = "response" to get predicted probabilities for each row.</span></span>
<span id="cb26-3"><a href="#cb26-3"></a>broom<span class="sc">::</span><span class="fu">augment</span>(mod) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,102 × 9
   cappun conservative weekly .fitted .resid     .hat .sigma  .cooksd .std.resid
    &lt;int&gt;        &lt;int&gt;  &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
 1      1            1      0  1.22    0.719 0.00165    1.13 0.000162      0.719
 2      1            1      0  1.22    0.719 0.00165    1.13 0.000162      0.719
 3      0            0      0  0.358  -1.33  0.000800   1.13 0.000382     -1.33 
 4      0            1      1  0.848  -1.55  0.00268    1.13 0.00209      -1.55 
 5      1            0      0  0.358   1.03  0.000800   1.13 0.000187      1.03 
 6      1            0      1 -0.0158  1.18  0.00288    1.13 0.000981      1.19 
 7      1            1      1  0.848   0.844 0.00268    1.13 0.000384      0.845
 8      1            0      0  0.358   1.03  0.000800   1.13 0.000187      1.03 
 9      1            1      0  1.22    0.719 0.00165    1.13 0.000162      0.719
10      1            0      0  0.358   1.03  0.000800   1.13 0.000187      1.03 
# ℹ 2,092 more rows</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Note. The <code>broom::augment()</code> works very similar to the built-in <code>predict()</code> function.</p>
</div>
</div>
</div>
<p>You can use augment to generate predicted probabilities for each row.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">augment</span>(mod) <span class="sc">|&gt;</span> </span>
<span id="cb28-2"><a href="#cb28-2"></a>  <span class="fu">distinct</span>(conservative, weekly, .fitted) <span class="sc">|&gt;</span> </span>
<span id="cb28-3"><a href="#cb28-3"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> <span class="fu">plogis</span>(.fitted))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  conservative weekly .fitted  prob
         &lt;int&gt;  &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;
1            1      0  1.22   0.772
2            0      0  0.358  0.589
3            1      1  0.848  0.700
4            0      1 -0.0158 0.496</code></pre>
</div>
</div>
<hr>
<p>The <a href="https://modelsummary.com/index.html">modelsummary</a> package, which allows for the creation of publication ready tables.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>modelsummary<span class="sc">::</span><span class="fu">msummary</span>(<span class="fu">list</span>(<span class="st">"Model 1"</span> <span class="ot">=</span> mod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Model 1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">0.358</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.057)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">conservative</td>
<td style="text-align: center;">0.864</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.105)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">weekly</td>
<td style="text-align: center;">−0.374</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.112)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">2102</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">2698.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">2715.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">−1346.112</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RMSE</td>
<td style="text-align: center;">0.47</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="looking-under-the-hood" class="level3" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="looking-under-the-hood"><span class="header-section-number">10.1.3</span> Looking Under the Hood</h3>
<p>I think it’s important to know how the <em>model formula</em> is reshaping your data frame.</p>
<p>The <code>glm()</code> function will create a matrix based on your data and the formula. You can see this by using the <code>model.matrix()</code> function.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">data =</span> d)</span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="fu">head</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) conservative weekly
1           1            1      0
2           1            1      0
3           1            0      0
4           1            1      1
5           1            0      0
6           1            0      1</code></pre>
</div>
</div>
<p>Matrix notation allows us to express our model more succinctly.</p>
<p>This expression</p>
<p><span class="math display">\[
\begin{align}
&amp;\text{logit}(\theta_i) = \alpha + \beta_1 \times \texttt{conservative}_i + \beta_2 \times \texttt{weekly}_i \\\\
&amp;\text{for } i = 1, 2, ..., n
\end{align}
\]</span></p>
<p>can be written as a matrix multiplication</p>
<p><span class="math display">\[
\text{logit}(\boldsymbol \theta) = \mathbf{X} \boldsymbol \beta
\]</span></p>
<p>where <span class="math inline">\(\mathbf{X}\)</span> is a <span class="math inline">\(2102 \times 3\)</span> matrix and <span class="math inline">\(\boldsymbol \beta\)</span> (in bold) is a vector that holds three parameters.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">dim</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2102    3</code></pre>
</div>
</div>
<p>Finally, R will use <em>some</em> optimization algorithm to efficiently find the three values contained in <span class="math inline">\(\boldsymbol \beta\)</span>.</p>
<hr>
<p>Click “Show me” if you want to see how this <em>might</em> happen. However, this is pretty advanced and you don’t really need to see “under the hood” to be able to drive a car. <em>I don’t expect anyone to fully understand what’s going on here.</em> However, I hope you can at least gain some appreciation for all the things the <code>glm()</code> function is doing for you.</p>
<div class="cell">
<details>
<summary>Show me</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="do">## a more general likelihood function</span></span>
<span id="cb35-2"><a href="#cb35-2"></a>log_likelihood_bernoulli <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, outcome, X) {</span>
<span id="cb35-3"><a href="#cb35-3"></a>  linpred <span class="ot">&lt;-</span> X <span class="sc">%*%</span> beta </span>
<span id="cb35-4"><a href="#cb35-4"></a>  theta <span class="ot">&lt;-</span> <span class="fu">plogis</span>(linpred)     </span>
<span id="cb35-5"><a href="#cb35-5"></a>  <span class="fu">return</span>(<span class="fu">sum</span>(<span class="fu">dbinom</span>(outcome, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> theta, <span class="at">log =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb35-6"><a href="#cb35-6"></a>}</span>
<span id="cb35-7"><a href="#cb35-7"></a></span>
<span id="cb35-8"><a href="#cb35-8"></a>opt <span class="ot">&lt;-</span> <span class="fu">optim</span>(</span>
<span id="cb35-9"><a href="#cb35-9"></a>  <span class="at">par =</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(X)),   <span class="do">## Sets all initial parameter values at zero</span></span>
<span id="cb35-10"><a href="#cb35-10"></a>  <span class="at">method =</span> <span class="st">"BFGS"</span>,         <span class="do">## The method used for optimization</span></span>
<span id="cb35-11"><a href="#cb35-11"></a>  <span class="do">## The Bernoulli log-likelihood function;</span></span>
<span id="cb35-12"><a href="#cb35-12"></a>  <span class="do">## it provides the stuff we want to maximize</span></span>
<span id="cb35-13"><a href="#cb35-13"></a>  <span class="at">fn =</span> log_likelihood_bernoulli,  </span>
<span id="cb35-14"><a href="#cb35-14"></a>  <span class="do">## These are the arguments for log_likelihood_bernoulli which we </span></span>
<span id="cb35-15"><a href="#cb35-15"></a>  <span class="do">## DO NOT want to estimate. This means optim() will look for</span></span>
<span id="cb35-16"><a href="#cb35-16"></a>  <span class="do">## the values of "beta" that maximize the log-likelihood.</span></span>
<span id="cb35-17"><a href="#cb35-17"></a>  <span class="at">outcome =</span> d<span class="sc">$</span>cappun, <span class="at">X =</span> X,</span>
<span id="cb35-18"><a href="#cb35-18"></a>  <span class="co"># This next line is critical: </span></span>
<span id="cb35-19"><a href="#cb35-19"></a>  <span class="co"># it tells R to maximize rather than minimize</span></span>
<span id="cb35-20"><a href="#cb35-20"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">fnscale =</span> <span class="sc">-</span><span class="dv">1</span>),</span>
<span id="cb35-21"><a href="#cb35-21"></a>  <span class="do">## this is used to calculate standard errors (if you wanted to)</span></span>
<span id="cb35-22"><a href="#cb35-22"></a>  <span class="at">hessian =</span> <span class="cn">TRUE</span> </span>
<span id="cb35-23"><a href="#cb35-23"></a>)</span>
<span id="cb35-24"><a href="#cb35-24"></a></span>
<span id="cb35-25"><a href="#cb35-25"></a><span class="fu">names</span>(opt<span class="sc">$</span>par) <span class="ot">&lt;-</span> <span class="fu">colnames</span>(X)</span>
<span id="cb35-26"><a href="#cb35-26"></a>opt<span class="sc">$</span>par</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) conservative       weekly 
   0.3583379    0.8639557   -0.3741452 </code></pre>
</div>
</div>
</section>
</section>
<section id="model-comparison" class="level2 page-columns page-full" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="model-comparison"><span class="header-section-number">10.2</span> Model Comparison</h2>
<p>We will focus on two measurements that will allow you to adjudicate between models based on their <em>predictive accuracy.</em></p>
<p>Both of them build upon the notion of <em><strong>deviance</strong>:</em></p>
<p><span class="math display">\[
D = \log(\text{likelihood}) \times -2
\]</span></p>
<p><strong>The Akaike Information Criteria</strong></p>
<p><span class="math display">\[
\text{AIC} = D + k \times 2
\]</span></p>
<aside>
<span class="math inline">\(k\)</span> is the number of parameters in the model
</aside>
<p><strong>The Bayesian Information Criteria</strong></p>
<p><span class="math display">\[
\text{BIC} = D + k \times \log(n)
\]</span></p>
<p><strong><em>Out-of-sample deviance</em></strong></p>
<p>Steve keeps saying that we <em>should</em> really care about how these models perform out-of-sample—i.e., how they are able to describe new observations. We don’t want to learn <em>too much</em> from our sample; otherwise it will perform poorly on new data <em>(over-fitting).</em> We also don’t want to learn <em>too little</em> from our sample <em>(under-fitting).</em></p>
<p>As it turns out, the AIC approximates the <em>out-of-sample deviance</em> of a model.</p>
<p><em>The AIC is “asymptotically” equivalent to the so-called leave-one-out cross validation (LOOCV).</em></p>
<p>With LOOCV we fit the same model repeatedly to a dataset that excludes one observation and then use the resulting model to calculate the log-likelihood on the observation we left out. Finally, we add up the log-likelihoods and multiply them by <span class="math inline">\(-2\)</span>, which means we are actually calculating a <em>deviance</em> based on the left-out observations.</p>
<p>The following chunk of code demonstrates this result.</p>
<div class="cell" data-hash="week10_cache/html/unnamed-chunk-18_cd0dee705f054fe5c30ec8f02e34c51b">
<details>
<summary>Show me</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="do">## we create an empty vessel to store the log-likelihoods for left-out obs</span></span>
<span id="cb37-2"><a href="#cb37-2"></a>out <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"double"</span>, <span class="fu">nrow</span>(d))</span>
<span id="cb37-3"><a href="#cb37-3"></a></span>
<span id="cb37-4"><a href="#cb37-4"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(d)) {</span>
<span id="cb37-5"><a href="#cb37-5"></a>  <span class="do">## note how we exclude the i observation using integer subsetting.</span></span>
<span id="cb37-6"><a href="#cb37-6"></a>  m <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> d[<span class="sc">-</span>i, ])</span>
<span id="cb37-7"><a href="#cb37-7"></a>  <span class="do">## then we get a prediction for the left-out observation</span></span>
<span id="cb37-8"><a href="#cb37-8"></a>  theta <span class="ot">&lt;-</span> <span class="fu">predict</span>(m, <span class="at">newdata =</span> d[i, ], <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb37-9"><a href="#cb37-9"></a>  <span class="do">## then we calculate the log-likelihood for the left-out observation</span></span>
<span id="cb37-10"><a href="#cb37-10"></a>  out[[i]] <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(d<span class="sc">$</span>cappun[[i]], <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> theta, <span class="at">log =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-11"><a href="#cb37-11"></a>}</span>
<span id="cb37-12"><a href="#cb37-12"></a></span>
<span id="cb37-13"><a href="#cb37-13"></a><span class="do">## deviance for the left-out observations</span></span>
<span id="cb37-14"><a href="#cb37-14"></a><span class="fu">sum</span>(out) <span class="sc">*</span> <span class="sc">-</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2698.251</code></pre>
</div>
</div>
<p>As a reminder, this is the AIC for the model we calculated earlier:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">AIC</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2698.224</code></pre>
</div>
</div>
<p><em>They are almost the same!</em></p>
<p>Thus, for most purposes, the AIC provides a good approximation for the out-of-sample deviance.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</section>
<section id="exercises" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="exercises"><span class="header-section-number">10.3</span> Exercises</h2>
<section id="exercise" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="exercise"><span class="header-section-number">10.3.1</span> Exercise</h3>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Describe how the following formulas are reshaping your data frame:</p>
<ul>
<li><p><code>cappun ~ polviews + weekly + polviews:weekly</code></p></li>
<li><p><code>cappun ~ polviews * weekly</code></p></li>
<li><p><code>cappun ~ degree</code></p></li>
</ul>
<p>Use the <code>model.matrix()</code> function to complement your answers.</p>
</div>
</div>
</div>
</section>
<section id="exercise-1" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="exercise-1"><span class="header-section-number">10.3.2</span> Exercise</h3>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><em>Compare the following models using AIC and BIC.</em></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb41-2"><a href="#cb41-2"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">*</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb41-3"><a href="#cb41-3"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> polviews <span class="sc">+</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb41-4"><a href="#cb41-4"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> polviews <span class="sc">*</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><em>Interpret the intercept in all models.</em></p>
<p><em>Looking at <code>mod4</code>, what is the predicted probability that a “slightly conservative” individual that attends religious ceremonies weekly favors capital punishment?</em></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Hint: You can create pretty coefficient tables with the <code>msummary()</code> function from the <code>modelsummary</code> package.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="fu">msummary</span>(<span class="fu">list</span>(mod1, mod2, mod3, mod4), <span class="at">gof_map =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(2)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(3)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(4)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">0.358</td>
<td style="text-align: center;">0.341</td>
<td style="text-align: center;">0.666</td>
<td style="text-align: center;">0.677</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.057)</td>
<td style="text-align: center;">(0.059)</td>
<td style="text-align: center;">(0.054)</td>
<td style="text-align: center;">(0.055)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">conservative</td>
<td style="text-align: center;">0.864</td>
<td style="text-align: center;">0.942</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.105)</td>
<td style="text-align: center;">(0.127)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">weekly</td>
<td style="text-align: center;">−0.374</td>
<td style="text-align: center;">−0.274</td>
<td style="text-align: center;">−0.488</td>
<td style="text-align: center;">−0.451</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.112)</td>
<td style="text-align: center;">(0.143)</td>
<td style="text-align: center;">(0.115)</td>
<td style="text-align: center;">(0.116)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">conservative × weekly</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.263</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.230)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">polviews</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.405</td>
<td style="text-align: center;">0.441</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.034)</td>
<td style="text-align: center;">(0.039)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">polviews × weekly</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.138</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.076)</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-2" class="level3" data-number="10.3.3">
<h3 data-number="10.3.3" class="anchored" data-anchor-id="exercise-2"><span class="header-section-number">10.3.3</span> Exercise</h3>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Transform <code>polviews</code> into a new variable that has the following three values:</p>
<p><span class="math display">\[
\texttt{polviews2} = \begin{cases}
\text{liberal} &amp;\text{if} &amp;\text{polviews} &lt; 0 \\
\text{moderate} &amp;\text{if} &amp;\text{polviews} == 0 \\
\text{conservative} &amp;\text{if} &amp;\text{polviews} &gt; 0
\end{cases}
\]</span></p>
<p>Fit the following model three times, choosing with a new reference category each time.</p>
<ul>
<li><code>cappun ~ polviews2 + weekly</code></li>
</ul>
<p>Interpret the coefficients.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Hint: You can create this variable by using two nested <code>if_else()</code> statements, but you might want to prefer using the <code>case_when()</code> function.</p>
<p><a href="https://dplyr.tidyverse.org/reference/case_when.html" class="uri">https://dplyr.tidyverse.org/reference/case_when.html</a></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Hint: You can change the reference category using the <code>fct_relevel()</code></p>
<p><a href="https://forcats.tidyverse.org/reference/fct_relevel.html" class="uri">https://forcats.tidyverse.org/reference/fct_relevel.html</a></p>
</div>
</div>
</div>
</section>
<section id="exercise-3" class="level3" data-number="10.3.4">
<h3 data-number="10.3.4" class="anchored" data-anchor-id="exercise-3"><span class="header-section-number">10.3.4</span> Exercise</h3>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Fill in the conditional probabilities in the following table:</p>
<table class="table">
<caption>Probability that a respondent favors capital punishment ( <span class="math inline">\(\texttt{cappun} = 1\)</span> )</caption>
<thead>
<tr class="header">
<th><code>weekly</code></th>
<th><code>polviews2</code></th>
<th>Saturated Model</th>
<th>Restricted Model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>liberal</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>0</td>
<td>moderate</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>0</td>
<td>conservative</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>1</td>
<td>liberal</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>1</td>
<td>moderate</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>1</td>
<td>conservative</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Hint: There are two ways to estimate the “saturated model”.</p>
<ul>
<li><p>Using the model formula that includes all interactions: <code>cappun ~ weekly*polviews2</code>.</p>
<p>Then you can use either <code>predict()</code> or <code>broom::augment()</code></p></li>
<li><p>Using <code>dplyr</code></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>d <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2"></a>  <span class="fu">group_by</span>(weekly, polviews2) <span class="sc">|&gt;</span> </span>
<span id="cb43-3"><a href="#cb43-3"></a>  <span class="fu">summarize</span>(<span class="at">p =</span> <span class="fu">mean</span>(cappun))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div></li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-4" class="level3" data-number="10.3.5">
<h3 data-number="10.3.5" class="anchored" data-anchor-id="exercise-4"><span class="header-section-number">10.3.5</span> Exercise</h3>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Do the following:</p>
<ul>
<li><p>Look at the GSS data and choose an outcome variable that interests you.</p></li>
<li><p>Choose 2 or 3 predictors that interests you.</p></li>
<li><p>Create at least two models and then compare them using AIC and BIC.</p>
<p>Which model has a better out-of-sample predictive accuracy?</p></li>
<li><p>What is the relationship between your outcome and your predictors?</p>
<p><em>Don’t worry about making causal claims unless you think they are reasonable.</em></p></li>
<li><p><em>Keep it simple! This is only a class exercise!</em></p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="extra" class="level3" data-number="10.3.6">
<h3 data-number="10.3.6" class="anchored" data-anchor-id="extra"><span class="header-section-number">10.3.6</span> Extra</h3>
<p>I was originally going to ask you to calculate the standard deviations for bootstrap sampling distributions corresponding to <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\beta_2\)</span> in <a href="#eq-restricted">Equation&nbsp;<span>10.1</span></a>. The plan was to show you that these values correspond to the “standard errors” shown in the regression output.</p>
<p>Unfortunately, I couldn’t find a way to do this easily with the <code>infer</code> package, so here’s the code to do it:</p>
<div class="cell" data-hash="week10_cache/html/unnamed-chunk-23_bf3f3728437037aff1c49a71b18f00eb">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a>boot_coef <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="at">n =</span> <span class="fl">2e3</span>, <span class="at">simplify =</span> <span class="cn">FALSE</span>, <span class="at">expr =</span> {</span>
<span id="cb44-2"><a href="#cb44-2"></a>  i <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(d), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-3"><a href="#cb44-3"></a>  m <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> d[i, ])</span>
<span id="cb44-4"><a href="#cb44-4"></a>  <span class="fu">coefficients</span>(m)</span>
<span id="cb44-5"><a href="#cb44-5"></a>}) <span class="sc">|&gt;</span> <span class="fu">bind_rows</span>()</span>
<span id="cb44-6"><a href="#cb44-6"></a></span>
<span id="cb44-7"><a href="#cb44-7"></a><span class="fu">glimpse</span>(boot_coef)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,000
Columns: 3
$ `(Intercept)` &lt;dbl&gt; 0.3920013, 0.2805224, 0.4845080, 0.3749796, 0.2677500, 0…
$ conservative  &lt;dbl&gt; 0.9230637, 0.8763783, 0.8171700, 1.0291167, 0.9559862, 0…
$ weekly        &lt;dbl&gt; -0.4231425, -0.3795132, -0.3303834, -0.3090928, -0.25411…</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a>boot_coef <span class="sc">|&gt;</span> </span>
<span id="cb46-2"><a href="#cb46-2"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"term"</span>, <span class="at">values_to =</span> <span class="st">"stat"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb46-3"><a href="#cb46-3"></a>  <span class="fu">group_by</span>(term) <span class="sc">|&gt;</span> </span>
<span id="cb46-4"><a href="#cb46-4"></a>  <span class="fu">summarize</span>(<span class="at">estimate =</span> <span class="fu">mean</span>(stat), <span class="at">std.error =</span> <span class="fu">sd</span>(stat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  term         estimate std.error
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)     0.359    0.0586
2 conservative    0.866    0.105 
3 weekly         -0.378    0.114 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term         estimate std.error statistic  p.value
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)     0.358    0.0575      6.23 4.56e-10
2 conservative    0.864    0.105       8.21 2.15e-16
3 weekly         -0.374    0.112      -3.33 8.58e- 4</code></pre>
</div>
</div>


<!-- -->

</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>This will not be the case if the data is structured weirdly—e.g., time-series, nested observations, etc.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./week09.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Week 9</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./sec-solutions.html" class="pagination-link">
        <span class="nav-page-text">Solutions</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb50" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb50-1"><a href="#cb50-1"></a><span class="co">---</span></span>
<span id="cb50-2"><a href="#cb50-2"></a><span class="an">title:</span><span class="co"> "Week 10"</span></span>
<span id="cb50-3"><a href="#cb50-3"></a><span class="an">callout-appearance:</span><span class="co"> simple</span></span>
<span id="cb50-4"><a href="#cb50-4"></a><span class="an">callout-icon:</span><span class="co"> false</span></span>
<span id="cb50-5"><a href="#cb50-5"></a><span class="co">---</span></span>
<span id="cb50-6"><a href="#cb50-6"></a></span>
<span id="cb50-7"><a href="#cb50-7"></a><span class="fu">## Model Estimation</span></span>
<span id="cb50-8"><a href="#cb50-8"></a></span>
<span id="cb50-9"><a href="#cb50-9"></a>I'm going to show you how to estimate the same model in slightly different ways.</span>
<span id="cb50-10"><a href="#cb50-10"></a></span>
<span id="cb50-11"><a href="#cb50-11"></a>Let's take four variables from the 2018 GSS:</span>
<span id="cb50-12"><a href="#cb50-12"></a></span>
<span id="cb50-13"><a href="#cb50-13"></a><span class="ss">-   </span><span class="in">`cappun`</span>: favor or oppose death penalty for murder.</span>
<span id="cb50-14"><a href="#cb50-14"></a></span>
<span id="cb50-15"><a href="#cb50-15"></a><span class="ss">-   </span><span class="in">`polviews`</span>: self-identification in a 7-point scale: extremely liberal (<span class="in">`1`</span>), liberal (<span class="in">`2`</span>), slightly liberal (<span class="in">`3`</span>), moderate (<span class="in">`4`</span>), slightly conservative (<span class="in">`5`</span>), conservative (<span class="in">`6`</span>), and extremely conservative (<span class="in">`7`</span>).</span>
<span id="cb50-16"><a href="#cb50-16"></a></span>
<span id="cb50-17"><a href="#cb50-17"></a><span class="ss">-   </span><span class="in">`attend`</span>: how often the respondent attends religious ceremonies: never (<span class="in">`0`</span>), less than once a year (<span class="in">`1`</span>), about once or twice a year (<span class="in">`2`</span>), several times a year (<span class="in">`3`</span>), about once a month (<span class="in">`4`</span>), 2-3 times a month (<span class="in">`5`</span>), nearly every week (<span class="in">`6`</span>), every week (<span class="in">`7`</span>), and several times a week (<span class="in">`8`</span>).</span>
<span id="cb50-18"><a href="#cb50-18"></a></span>
<span id="cb50-19"><a href="#cb50-19"></a><span class="ss">-   </span><span class="in">`degree`</span>: respondent's highest degree. We will keep this variable as a *factor* variable---i.e., a kind of character vector which can be *ordered* and that plays well with R's *model formula* syntax.</span>
<span id="cb50-20"><a href="#cb50-20"></a></span>
<span id="cb50-23"><a href="#cb50-23"></a><span class="in">```{r}</span></span>
<span id="cb50-24"><a href="#cb50-24"></a><span class="co">#| message: false</span></span>
<span id="cb50-25"><a href="#cb50-25"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb50-26"><a href="#cb50-26"></a><span class="fu">theme_set</span>(<span class="fu">theme_light</span>(<span class="at">base_family =</span> <span class="st">"Optima"</span>))</span>
<span id="cb50-27"><a href="#cb50-27"></a></span>
<span id="cb50-28"><a href="#cb50-28"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb50-29"><a href="#cb50-29"></a><span class="fu">library</span>(broom)</span>
<span id="cb50-30"><a href="#cb50-30"></a></span>
<span id="cb50-31"><a href="#cb50-31"></a><span class="fu">library</span>(gssr)</span>
<span id="cb50-32"><a href="#cb50-32"></a>gss18 <span class="ot">&lt;-</span> <span class="fu">gss_get_yr</span>(<span class="dv">2018</span>) </span>
<span id="cb50-33"><a href="#cb50-33"></a></span>
<span id="cb50-34"><a href="#cb50-34"></a>d <span class="ot">&lt;-</span> gss18 <span class="sc">|&gt;</span> </span>
<span id="cb50-35"><a href="#cb50-35"></a>  <span class="fu">select</span>(attend, polviews, cappun, degree) <span class="sc">|&gt;</span> </span>
<span id="cb50-36"><a href="#cb50-36"></a>  haven<span class="sc">::</span><span class="fu">zap_missing</span>() <span class="sc">|&gt;</span> </span>
<span id="cb50-37"><a href="#cb50-37"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">!</span>degree, haven<span class="sc">::</span>zap_labels)) <span class="sc">|&gt;</span> </span>
<span id="cb50-38"><a href="#cb50-38"></a>  <span class="fu">mutate</span>(<span class="at">degree =</span> haven<span class="sc">::</span><span class="fu">as_factor</span>(degree)) <span class="sc">|&gt;</span> </span>
<span id="cb50-39"><a href="#cb50-39"></a>  <span class="fu">mutate</span>(</span>
<span id="cb50-40"><a href="#cb50-40"></a>    <span class="at">weekly =</span> <span class="fu">if_else</span>(attend <span class="sc">&gt;=</span> <span class="dv">7</span>, 1L, 0L),</span>
<span id="cb50-41"><a href="#cb50-41"></a>    <span class="at">polviews =</span> polviews <span class="sc">-</span> <span class="dv">4</span>,</span>
<span id="cb50-42"><a href="#cb50-42"></a>    <span class="at">cappun =</span> <span class="fu">if_else</span>(cappun <span class="sc">==</span> <span class="dv">1</span>, 1L, 0L),</span>
<span id="cb50-43"><a href="#cb50-43"></a>    ) <span class="sc">|&gt;</span> </span>
<span id="cb50-44"><a href="#cb50-44"></a>  <span class="fu">mutate</span>(<span class="at">conservative =</span> <span class="fu">as.integer</span>(polviews <span class="sc">&gt;</span> <span class="dv">0</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb50-45"><a href="#cb50-45"></a>  <span class="fu">drop_na</span>() </span>
<span id="cb50-46"><a href="#cb50-46"></a></span>
<span id="cb50-47"><a href="#cb50-47"></a>d</span>
<span id="cb50-48"><a href="#cb50-48"></a><span class="in">```</span></span>
<span id="cb50-49"><a href="#cb50-49"></a></span>
<span id="cb50-50"><a href="#cb50-50"></a>Note that in the previous code we created two additional variables and *transformed* <span class="in">`polviews`</span>:</span>
<span id="cb50-51"><a href="#cb50-51"></a></span>
<span id="cb50-52"><a href="#cb50-52"></a><span class="ss">-   </span><span class="in">`weekly`</span>: attends religious ceremonies one or more times a week</span>
<span id="cb50-53"><a href="#cb50-53"></a></span>
<span id="cb50-54"><a href="#cb50-54"></a><span class="ss">-   </span><span class="in">`polviews`</span>: this variable is now centered at 0.</span>
<span id="cb50-55"><a href="#cb50-55"></a></span>
<span id="cb50-56"><a href="#cb50-56"></a><span class="ss">-   </span><span class="in">`conservative`</span>: slightly conservative, conservative, and extremely conservative.</span>
<span id="cb50-57"><a href="#cb50-57"></a></span>
<span id="cb50-58"><a href="#cb50-58"></a>Last week we learned that we could estimate a "saturated model" by hand by looking at the conditional probabilities in a $2 \times 2 \times 2$ contingency table. This week, we learned how to estimated a "restricted model" like the one in @eq-restricted. This time, however, we can't calculate the parameters in the model by hand.</span>
<span id="cb50-59"><a href="#cb50-59"></a></span>
<span id="cb50-60"><a href="#cb50-60"></a>$$</span>
<span id="cb50-61"><a href="#cb50-61"></a>\log \Bigg( \frac{\Pr(\texttt{cappun}_i = 1)}{1-\Pr(\texttt{cappun}_i = 1)} \Bigg) = \alpha + \beta_1 \times \texttt{conservative}_i + \beta_2 \times \texttt{weekly}_i</span>
<span id="cb50-62"><a href="#cb50-62"></a>$$ {#eq-restricted}</span>
<span id="cb50-63"><a href="#cb50-63"></a></span>
<span id="cb50-64"><a href="#cb50-64"></a>Here, we want to choose the parameters $\alpha$, $\beta_1$, and $\beta_2$ that maximize the *joint probability* of the observed data. Strictly speaking, we want choose the parameters that maximize the following expression:</span>
<span id="cb50-65"><a href="#cb50-65"></a></span>
<span id="cb50-66"><a href="#cb50-66"></a>$$</span>
<span id="cb50-67"><a href="#cb50-67"></a>\text{log-likelihood} = \texttt{sum(dbinom(} \boldsymbol{y} \texttt{, size = 1, prob = } \boldsymbol {\theta} \texttt{, log = TRUE))}</span>
<span id="cb50-68"><a href="#cb50-68"></a>$$ {#eq-logLik}</span>
<span id="cb50-69"><a href="#cb50-69"></a></span>
<span id="cb50-70"><a href="#cb50-70"></a>::: callout-tip</span>
<span id="cb50-71"><a href="#cb50-71"></a>We usually refer to this expression like this as a "probability" when the parameter $\theta$ is fixed and we are interested in making inferences about *unknown observations*; we refer to it as a "likelihood" when the data $y$ is fixed and we are interested in making inferences about *unknown parameters*.</span>
<span id="cb50-72"><a href="#cb50-72"></a>:::</span>
<span id="cb50-73"><a href="#cb50-73"></a></span>
<span id="cb50-74"><a href="#cb50-74"></a>Note that both $\boldsymbol y$ and $\theta$ are vectors of size 2102 (the number of observations in the data frame). Each individual $\theta_i$ is modeled as a function of our *predictors,* which are linear in the "logit" scale.</span>
<span id="cb50-75"><a href="#cb50-75"></a></span>
<span id="cb50-76"><a href="#cb50-76"></a>$$</span>
<span id="cb50-77"><a href="#cb50-77"></a>\text{logit}(\theta_i) = \alpha + \beta_1 \times \texttt{conservative}_i + \beta_2 \times \texttt{weekly}_i</span>
<span id="cb50-78"><a href="#cb50-78"></a>$$</span>
<span id="cb50-79"><a href="#cb50-79"></a></span>
<span id="cb50-80"><a href="#cb50-80"></a>How, then, do we estimate the parameters in our restricted model?</span>
<span id="cb50-81"><a href="#cb50-81"></a></span>
<span id="cb50-82"><a href="#cb50-82"></a><span class="fu">### Grid Search</span></span>
<span id="cb50-83"><a href="#cb50-83"></a></span>
<span id="cb50-84"><a href="#cb50-84"></a>Conceptually, the easiest way to estimate these parameters is by doing what's called a "grid search." This is also the *most inefficient* way to do it from a computational point of view.</span>
<span id="cb50-85"><a href="#cb50-85"></a></span>
<span id="cb50-86"><a href="#cb50-86"></a>We can create a "grid" like this:</span>
<span id="cb50-87"><a href="#cb50-87"></a></span>
<span id="cb50-90"><a href="#cb50-90"></a><span class="in">```{r}</span></span>
<span id="cb50-91"><a href="#cb50-91"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb50-92"><a href="#cb50-92"></a>  <span class="at">alpha =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.02</span>), </span>
<span id="cb50-93"><a href="#cb50-93"></a>  <span class="at">beta1 =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.02</span>),</span>
<span id="cb50-94"><a href="#cb50-94"></a>  <span class="at">beta2 =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.02</span>)</span>
<span id="cb50-95"><a href="#cb50-95"></a>)</span>
<span id="cb50-96"><a href="#cb50-96"></a></span>
<span id="cb50-97"><a href="#cb50-97"></a>grid</span>
<span id="cb50-98"><a href="#cb50-98"></a><span class="in">```</span></span>
<span id="cb50-99"><a href="#cb50-99"></a></span>
<span id="cb50-100"><a href="#cb50-100"></a>We will calculate the sum of log-likelihoods ( $ll$ ) for each row in this grid, and then choose the combination that produces the maximum value in @eq-logLik.</span>
<span id="cb50-101"><a href="#cb50-101"></a></span>
<span id="cb50-102"><a href="#cb50-102"></a>$$</span>
<span id="cb50-103"><a href="#cb50-103"></a>\underset{\alpha, \beta_1, \beta_2}{\arg \max} \ \texttt{log-likelihood}</span>
<span id="cb50-104"><a href="#cb50-104"></a>$$</span>
<span id="cb50-105"><a href="#cb50-105"></a></span>
<span id="cb50-106"><a href="#cb50-106"></a>To do so I will rely on this custom function (which you'll never see again):</span>
<span id="cb50-107"><a href="#cb50-107"></a></span>
<span id="cb50-110"><a href="#cb50-110"></a><span class="in">```{r}</span></span>
<span id="cb50-111"><a href="#cb50-111"></a>log_likelihood_cappun <span class="ot">&lt;-</span> <span class="cf">function</span>(alpha, beta1, beta2) {</span>
<span id="cb50-112"><a href="#cb50-112"></a>  </span>
<span id="cb50-113"><a href="#cb50-113"></a>  <span class="do">## the linear part of the model</span></span>
<span id="cb50-114"><a href="#cb50-114"></a>  <span class="do">## make sure that `d` exists in the global environment!</span></span>
<span id="cb50-115"><a href="#cb50-115"></a>  linpred <span class="ot">&lt;-</span> alpha <span class="sc">+</span> beta1 <span class="sc">*</span> d<span class="sc">$</span>conservative <span class="sc">+</span> beta2 <span class="sc">*</span> d<span class="sc">$</span>weekly</span>
<span id="cb50-116"><a href="#cb50-116"></a>  </span>
<span id="cb50-117"><a href="#cb50-117"></a>  <span class="do">## the inverse-logit transformation</span></span>
<span id="cb50-118"><a href="#cb50-118"></a>  theta <span class="ot">&lt;-</span> <span class="fu">exp</span>(linpred) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(linpred))</span>
<span id="cb50-119"><a href="#cb50-119"></a>  </span>
<span id="cb50-120"><a href="#cb50-120"></a>  <span class="do">## the sum of the log-likelihoods;</span></span>
<span id="cb50-121"><a href="#cb50-121"></a>  <span class="do">## we ultimately want coefficients that maximize this value</span></span>
<span id="cb50-122"><a href="#cb50-122"></a>  <span class="fu">return</span>(<span class="fu">sum</span>(<span class="fu">dbinom</span>(d<span class="sc">$</span>cappun, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> theta, <span class="at">log =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb50-123"><a href="#cb50-123"></a>  </span>
<span id="cb50-124"><a href="#cb50-124"></a>}</span>
<span id="cb50-125"><a href="#cb50-125"></a><span class="in">```</span></span>
<span id="cb50-126"><a href="#cb50-126"></a></span>
<span id="cb50-127"><a href="#cb50-127"></a>Now we apply the function to each row of the grid. There are more than a million rows, so it might take a few minutes!</span>
<span id="cb50-128"><a href="#cb50-128"></a></span>
<span id="cb50-131"><a href="#cb50-131"></a><span class="in">```{r}</span></span>
<span id="cb50-132"><a href="#cb50-132"></a><span class="co">#| cache: true</span></span>
<span id="cb50-133"><a href="#cb50-133"></a>out <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"double"</span>, <span class="fu">nrow</span>(grid)) <span class="do">## create empty vector</span></span>
<span id="cb50-134"><a href="#cb50-134"></a></span>
<span id="cb50-135"><a href="#cb50-135"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(out)) {  <span class="do">## this will be a slow process!!</span></span>
<span id="cb50-136"><a href="#cb50-136"></a>  out[[i]] <span class="ot">&lt;-</span> <span class="fu">log_likelihood_cappun</span>(grid<span class="sc">$</span>alpha[[i]], grid<span class="sc">$</span>beta1[[i]], grid<span class="sc">$</span>beta2[[i]])</span>
<span id="cb50-137"><a href="#cb50-137"></a>}</span>
<span id="cb50-138"><a href="#cb50-138"></a></span>
<span id="cb50-139"><a href="#cb50-139"></a>grid<span class="sc">$</span>ll <span class="ot">&lt;-</span> out</span>
<span id="cb50-140"><a href="#cb50-140"></a><span class="in">```</span></span>
<span id="cb50-141"><a href="#cb50-141"></a></span>
<span id="cb50-142"><a href="#cb50-142"></a>Finally, we search for the maximum value of <span class="in">`ll`</span> using the <span class="in">`filter()`</span> function from the dplyr package.</span>
<span id="cb50-143"><a href="#cb50-143"></a></span>
<span id="cb50-146"><a href="#cb50-146"></a><span class="in">```{r}</span></span>
<span id="cb50-147"><a href="#cb50-147"></a>grid <span class="sc">|&gt;</span> <span class="fu">filter</span>(ll <span class="sc">==</span> <span class="fu">max</span>(ll))</span>
<span id="cb50-148"><a href="#cb50-148"></a><span class="in">```</span></span>
<span id="cb50-149"><a href="#cb50-149"></a></span>
<span id="cb50-150"><a href="#cb50-150"></a>Hopefully you can see why this form of estimation looks a little bit like mountain climbing.</span>
<span id="cb50-151"><a href="#cb50-151"></a></span>
<span id="cb50-154"><a href="#cb50-154"></a><span class="in">```{r}</span></span>
<span id="cb50-155"><a href="#cb50-155"></a><span class="co">#| code-fold: true</span></span>
<span id="cb50-156"><a href="#cb50-156"></a>grid <span class="sc">|&gt;</span> </span>
<span id="cb50-157"><a href="#cb50-157"></a>  <span class="fu">filter</span>(<span class="fu">near</span>(alpha, <span class="fl">0.36</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb50-158"><a href="#cb50-158"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(beta1, beta2)) <span class="sc">+</span> </span>
<span id="cb50-159"><a href="#cb50-159"></a>  <span class="fu">geom_tile</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ll)) <span class="sc">+</span> </span>
<span id="cb50-160"><a href="#cb50-160"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> <span class="fu">filter</span>(grid, ll <span class="sc">==</span> <span class="fu">max</span>(ll)), <span class="at">size =</span> <span class="dv">4</span>, <span class="at">pch =</span> <span class="dv">13</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb50-161"><a href="#cb50-161"></a>  <span class="fu">geom_contour</span>(<span class="fu">aes</span>(<span class="at">z =</span> ll), <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> </span>
<span id="cb50-162"><a href="#cb50-162"></a>  <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb50-163"><a href="#cb50-163"></a>  <span class="fu">labs</span>(</span>
<span id="cb50-164"><a href="#cb50-164"></a>    <span class="at">title =</span> <span class="st">"Mountain Climbing"</span>, </span>
<span id="cb50-165"><a href="#cb50-165"></a>    <span class="at">fill =</span> <span class="st">"log-likelihood"</span>,</span>
<span id="cb50-166"><a href="#cb50-166"></a>    <span class="at">x =</span> latex2exp<span class="sc">::</span><span class="fu">TeX</span>(<span class="st">"$</span><span class="sc">\\</span><span class="st">beta_1$"</span>), </span>
<span id="cb50-167"><a href="#cb50-167"></a>    <span class="at">y =</span> latex2exp<span class="sc">::</span><span class="fu">TeX</span>(<span class="st">"$</span><span class="sc">\\</span><span class="st">beta_2$"</span>)</span>
<span id="cb50-168"><a href="#cb50-168"></a>  )</span>
<span id="cb50-169"><a href="#cb50-169"></a><span class="in">```</span></span>
<span id="cb50-170"><a href="#cb50-170"></a></span>
<span id="cb50-171"><a href="#cb50-171"></a>*Note. Unlike what we did last week, there's no way to calculate these parameter values by hand.*</span>
<span id="cb50-172"><a href="#cb50-172"></a></span>
<span id="cb50-173"><a href="#cb50-173"></a><span class="fu">### The Easy Way</span></span>
<span id="cb50-174"><a href="#cb50-174"></a></span>
<span id="cb50-175"><a href="#cb50-175"></a>The easiest way to estimate this model is with R's built-in <span class="in">`glm`</span> function. This stands for *generalized linear regression*. The word "generalized" should serve as foreshadowing. *Everything we learn here can be extended to the modeling other types of outcome variables (not just binary).*</span>
<span id="cb50-176"><a href="#cb50-176"></a></span>
<span id="cb50-177"><a href="#cb50-177"></a>To use it we do three things:</span>
<span id="cb50-178"><a href="#cb50-178"></a></span>
<span id="cb50-179"><a href="#cb50-179"></a><span class="ss">1.  </span>Specify a *model formula* with a tilde ( <span class="in">`~`</span> ) separating the outcome variable (left-hand side) from the predictors (right-hand side).</span>
<span id="cb50-180"><a href="#cb50-180"></a><span class="ss">2.  </span>Specify the <span class="in">`data`</span> argument. An error will show up if the variables you specified in the formula don't exist in the data.</span>
<span id="cb50-181"><a href="#cb50-181"></a><span class="ss">3.  </span>Specify the <span class="in">`family`</span> argument. For a logistic regression this will always be "binomial."</span>
<span id="cb50-182"><a href="#cb50-182"></a></span>
<span id="cb50-183"><a href="#cb50-183"></a>Let's save the resulting object as <span class="in">`mod`</span>:</span>
<span id="cb50-184"><a href="#cb50-184"></a></span>
<span id="cb50-187"><a href="#cb50-187"></a><span class="in">```{r}</span></span>
<span id="cb50-188"><a href="#cb50-188"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb50-189"><a href="#cb50-189"></a>mod</span>
<span id="cb50-190"><a href="#cb50-190"></a><span class="in">```</span></span>
<span id="cb50-191"><a href="#cb50-191"></a></span>
<span id="cb50-192"><a href="#cb50-192"></a>You can see a lot of useful information here, including the Deviance, the Null Deviance, and the AIC.</span>
<span id="cb50-193"><a href="#cb50-193"></a></span>
<span id="cb50-194"><a href="#cb50-194"></a>As a reminder:</span>
<span id="cb50-195"><a href="#cb50-195"></a></span>
<span id="cb50-196"><a href="#cb50-196"></a><span class="ss">-   </span>The AIC is the *deviance* plus twice the number of parameters:</span>
<span id="cb50-197"><a href="#cb50-197"></a></span>
<span id="cb50-198"><a href="#cb50-198"></a>    $$</span>
<span id="cb50-199"><a href="#cb50-199"></a>    \text{AIC} = D + 2k</span>
<span id="cb50-200"><a href="#cb50-200"></a>    $$</span>
<span id="cb50-201"><a href="#cb50-201"></a></span>
<span id="cb50-202"><a href="#cb50-202"></a>    So 2692 + 6.</span>
<span id="cb50-203"><a href="#cb50-203"></a></span>
<span id="cb50-204"><a href="#cb50-204"></a><span class="ss">-   </span>The *deviance* is just the log-likelihood multiplied by -2.</span>
<span id="cb50-205"><a href="#cb50-205"></a></span>
<span id="cb50-206"><a href="#cb50-206"></a>    You can look at the log-likelihood by using the <span class="in">`logLik()`</span> function. It should roughly correspond to the <span class="in">`ll`</span> value we calculated earlier doing the grid search.</span>
<span id="cb50-207"><a href="#cb50-207"></a></span>
<span id="cb50-208"><a href="#cb50-208"></a>    <span class="in">```{r}</span></span>
<span id="cb50-209"><a href="#cb50-209"></a>    <span class="fu">logLik</span>(mod)</span>
<span id="cb50-210"><a href="#cb50-210"></a>    <span class="in">```</span></span>
<span id="cb50-211"><a href="#cb50-211"></a></span>
<span id="cb50-212"><a href="#cb50-212"></a><span class="ss">-   </span>The *null deviance* corresponds to a model with no predictors.</span>
<span id="cb50-213"><a href="#cb50-213"></a></span>
<span id="cb50-214"><a href="#cb50-214"></a>    *You should be able to calculate this very easily! It's going back to univariate statistics!*</span>
<span id="cb50-215"><a href="#cb50-215"></a></span>
<span id="cb50-216"><a href="#cb50-216"></a>    <span class="in">```{r}</span></span>
<span id="cb50-217"><a href="#cb50-217"></a>    nullll <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">dbinom</span>(d<span class="sc">$</span>cappun, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fu">mean</span>(d<span class="sc">$</span>cappun), <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb50-218"><a href="#cb50-218"></a>    nullll <span class="sc">*</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb50-219"><a href="#cb50-219"></a>    <span class="in">```</span></span>
<span id="cb50-220"><a href="#cb50-220"></a></span>
<span id="cb50-221"><a href="#cb50-221"></a>Sometimes you'll see people use the <span class="in">`summary()`</span> function to get even *more* information.</span>
<span id="cb50-222"><a href="#cb50-222"></a></span>
<span id="cb50-225"><a href="#cb50-225"></a><span class="in">```{r}</span></span>
<span id="cb50-226"><a href="#cb50-226"></a><span class="fu">summary</span>(mod)</span>
<span id="cb50-227"><a href="#cb50-227"></a><span class="in">```</span></span>
<span id="cb50-228"><a href="#cb50-228"></a></span>
<span id="cb50-229"><a href="#cb50-229"></a>Or you'll see people using the <span class="in">`coef()`</span>---or <span class="in">`coefficients()`</span>---functions to extract the parameter values.</span>
<span id="cb50-230"><a href="#cb50-230"></a></span>
<span id="cb50-233"><a href="#cb50-233"></a><span class="in">```{r}</span></span>
<span id="cb50-234"><a href="#cb50-234"></a><span class="fu">coef</span>(mod)</span>
<span id="cb50-235"><a href="#cb50-235"></a><span class="fu">coefficients</span>(mod)</span>
<span id="cb50-236"><a href="#cb50-236"></a><span class="in">```</span></span>
<span id="cb50-237"><a href="#cb50-237"></a></span>
<span id="cb50-238"><a href="#cb50-238"></a>There are also some useful packages that work seamlessly with <span class="in">`glm`</span>.</span>
<span id="cb50-239"><a href="#cb50-239"></a></span>
<span id="cb50-240"><a href="#cb50-240"></a>------------------------------------------------------------------------</span>
<span id="cb50-241"><a href="#cb50-241"></a></span>
<span id="cb50-242"><a href="#cb50-242"></a>The <span class="co">[</span><span class="ot">broom</span><span class="co">](https://broom.tidymodels.org/)</span> package, with it's associated three functions.</span>
<span id="cb50-243"><a href="#cb50-243"></a></span>
<span id="cb50-246"><a href="#cb50-246"></a><span class="in">```{r}</span></span>
<span id="cb50-247"><a href="#cb50-247"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(mod)</span>
<span id="cb50-248"><a href="#cb50-248"></a>broom<span class="sc">::</span><span class="fu">glance</span>(mod)</span>
<span id="cb50-249"><a href="#cb50-249"></a><span class="do">## the .fitted values are predictions in log-odds</span></span>
<span id="cb50-250"><a href="#cb50-250"></a><span class="do">## add type.predict = "response" to get predicted probabilities for each row.</span></span>
<span id="cb50-251"><a href="#cb50-251"></a>broom<span class="sc">::</span><span class="fu">augment</span>(mod) </span>
<span id="cb50-252"><a href="#cb50-252"></a><span class="in">```</span></span>
<span id="cb50-253"><a href="#cb50-253"></a></span>
<span id="cb50-254"><a href="#cb50-254"></a>::: callout-tip</span>
<span id="cb50-255"><a href="#cb50-255"></a>Note. The <span class="in">`broom::augment()`</span> works very similar to the built-in <span class="in">`predict()`</span> function.</span>
<span id="cb50-256"><a href="#cb50-256"></a>:::</span>
<span id="cb50-257"><a href="#cb50-257"></a></span>
<span id="cb50-258"><a href="#cb50-258"></a>You can use augment to generate predicted probabilities for each row.</span>
<span id="cb50-259"><a href="#cb50-259"></a></span>
<span id="cb50-262"><a href="#cb50-262"></a><span class="in">```{r}</span></span>
<span id="cb50-263"><a href="#cb50-263"></a><span class="fu">augment</span>(mod) <span class="sc">|&gt;</span> </span>
<span id="cb50-264"><a href="#cb50-264"></a>  <span class="fu">distinct</span>(conservative, weekly, .fitted) <span class="sc">|&gt;</span> </span>
<span id="cb50-265"><a href="#cb50-265"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> <span class="fu">plogis</span>(.fitted))</span>
<span id="cb50-266"><a href="#cb50-266"></a><span class="in">```</span></span>
<span id="cb50-267"><a href="#cb50-267"></a></span>
<span id="cb50-268"><a href="#cb50-268"></a>------------------------------------------------------------------------</span>
<span id="cb50-269"><a href="#cb50-269"></a></span>
<span id="cb50-270"><a href="#cb50-270"></a>The <span class="co">[</span><span class="ot">modelsummary</span><span class="co">](https://modelsummary.com/index.html)</span> package, which allows for the creation of publication ready tables.</span>
<span id="cb50-271"><a href="#cb50-271"></a></span>
<span id="cb50-274"><a href="#cb50-274"></a><span class="in">```{r}</span></span>
<span id="cb50-275"><a href="#cb50-275"></a>modelsummary<span class="sc">::</span><span class="fu">msummary</span>(<span class="fu">list</span>(<span class="st">"Model 1"</span> <span class="ot">=</span> mod))</span>
<span id="cb50-276"><a href="#cb50-276"></a><span class="in">```</span></span>
<span id="cb50-277"><a href="#cb50-277"></a></span>
<span id="cb50-278"><a href="#cb50-278"></a><span class="fu">### Looking Under the Hood</span></span>
<span id="cb50-279"><a href="#cb50-279"></a></span>
<span id="cb50-280"><a href="#cb50-280"></a>I think it's important to know how the *model formula* is reshaping your data frame.</span>
<span id="cb50-281"><a href="#cb50-281"></a></span>
<span id="cb50-282"><a href="#cb50-282"></a>The <span class="in">`glm()`</span> function will create a matrix based on your data and the formula. You can see this by using the <span class="in">`model.matrix()`</span> function.</span>
<span id="cb50-283"><a href="#cb50-283"></a></span>
<span id="cb50-286"><a href="#cb50-286"></a><span class="in">```{r}</span></span>
<span id="cb50-287"><a href="#cb50-287"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">data =</span> d)</span>
<span id="cb50-288"><a href="#cb50-288"></a><span class="fu">head</span>(X)</span>
<span id="cb50-289"><a href="#cb50-289"></a><span class="in">```</span></span>
<span id="cb50-290"><a href="#cb50-290"></a></span>
<span id="cb50-291"><a href="#cb50-291"></a>Matrix notation allows us to express our model more succinctly.</span>
<span id="cb50-292"><a href="#cb50-292"></a></span>
<span id="cb50-293"><a href="#cb50-293"></a>This expression</span>
<span id="cb50-294"><a href="#cb50-294"></a></span>
<span id="cb50-295"><a href="#cb50-295"></a>$$</span>
<span id="cb50-296"><a href="#cb50-296"></a>\begin{align}</span>
<span id="cb50-297"><a href="#cb50-297"></a>&amp;\text{logit}(\theta_i) = \alpha + \beta_1 \times \texttt{conservative}_i + \beta_2 \times \texttt{weekly}_i <span class="sc">\\\\</span></span>
<span id="cb50-298"><a href="#cb50-298"></a>&amp;\text{for } i = 1, 2, ..., n</span>
<span id="cb50-299"><a href="#cb50-299"></a>\end{align}</span>
<span id="cb50-300"><a href="#cb50-300"></a>$$</span>
<span id="cb50-301"><a href="#cb50-301"></a></span>
<span id="cb50-302"><a href="#cb50-302"></a>can be written as a matrix multiplication</span>
<span id="cb50-303"><a href="#cb50-303"></a></span>
<span id="cb50-304"><a href="#cb50-304"></a>$$</span>
<span id="cb50-305"><a href="#cb50-305"></a>\text{logit}(\boldsymbol \theta) = \mathbf{X} \boldsymbol \beta</span>
<span id="cb50-306"><a href="#cb50-306"></a>$$</span>
<span id="cb50-307"><a href="#cb50-307"></a></span>
<span id="cb50-308"><a href="#cb50-308"></a>where $\mathbf{X}$ is a $2102 \times 3$ matrix and $\boldsymbol \beta$ (in bold) is a vector that holds three parameters.</span>
<span id="cb50-309"><a href="#cb50-309"></a></span>
<span id="cb50-312"><a href="#cb50-312"></a><span class="in">```{r}</span></span>
<span id="cb50-313"><a href="#cb50-313"></a><span class="fu">dim</span>(X)</span>
<span id="cb50-314"><a href="#cb50-314"></a><span class="in">```</span></span>
<span id="cb50-315"><a href="#cb50-315"></a></span>
<span id="cb50-316"><a href="#cb50-316"></a>Finally, R will use *some* optimization algorithm to efficiently find the three values contained in $\boldsymbol \beta$.</span>
<span id="cb50-317"><a href="#cb50-317"></a></span>
<span id="cb50-318"><a href="#cb50-318"></a>------------------------------------------------------------------------</span>
<span id="cb50-319"><a href="#cb50-319"></a></span>
<span id="cb50-320"><a href="#cb50-320"></a>Click "Show me" if you want to see how this *might* happen. However, this is pretty advanced and you don't really need to see "under the hood" to be able to drive a car. *I don't expect anyone to fully understand what's going on here.* However, I hope you can at least gain some appreciation for all the things the <span class="in">`glm()`</span> function is doing for you.</span>
<span id="cb50-321"><a href="#cb50-321"></a></span>
<span id="cb50-324"><a href="#cb50-324"></a><span class="in">```{r}</span></span>
<span id="cb50-325"><a href="#cb50-325"></a><span class="co">#| code-fold: true</span></span>
<span id="cb50-326"><a href="#cb50-326"></a><span class="co">#| code-summary: "Show me"</span></span>
<span id="cb50-327"><a href="#cb50-327"></a></span>
<span id="cb50-328"><a href="#cb50-328"></a><span class="do">## a more general likelihood function</span></span>
<span id="cb50-329"><a href="#cb50-329"></a>log_likelihood_bernoulli <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, outcome, X) {</span>
<span id="cb50-330"><a href="#cb50-330"></a>  linpred <span class="ot">&lt;-</span> X <span class="sc">%*%</span> beta </span>
<span id="cb50-331"><a href="#cb50-331"></a>  theta <span class="ot">&lt;-</span> <span class="fu">plogis</span>(linpred)     </span>
<span id="cb50-332"><a href="#cb50-332"></a>  <span class="fu">return</span>(<span class="fu">sum</span>(<span class="fu">dbinom</span>(outcome, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> theta, <span class="at">log =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb50-333"><a href="#cb50-333"></a>}</span>
<span id="cb50-334"><a href="#cb50-334"></a></span>
<span id="cb50-335"><a href="#cb50-335"></a>opt <span class="ot">&lt;-</span> <span class="fu">optim</span>(</span>
<span id="cb50-336"><a href="#cb50-336"></a>  <span class="at">par =</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(X)),   <span class="do">## Sets all initial parameter values at zero</span></span>
<span id="cb50-337"><a href="#cb50-337"></a>  <span class="at">method =</span> <span class="st">"BFGS"</span>,         <span class="do">## The method used for optimization</span></span>
<span id="cb50-338"><a href="#cb50-338"></a>  <span class="do">## The Bernoulli log-likelihood function;</span></span>
<span id="cb50-339"><a href="#cb50-339"></a>  <span class="do">## it provides the stuff we want to maximize</span></span>
<span id="cb50-340"><a href="#cb50-340"></a>  <span class="at">fn =</span> log_likelihood_bernoulli,  </span>
<span id="cb50-341"><a href="#cb50-341"></a>  <span class="do">## These are the arguments for log_likelihood_bernoulli which we </span></span>
<span id="cb50-342"><a href="#cb50-342"></a>  <span class="do">## DO NOT want to estimate. This means optim() will look for</span></span>
<span id="cb50-343"><a href="#cb50-343"></a>  <span class="do">## the values of "beta" that maximize the log-likelihood.</span></span>
<span id="cb50-344"><a href="#cb50-344"></a>  <span class="at">outcome =</span> d<span class="sc">$</span>cappun, <span class="at">X =</span> X,</span>
<span id="cb50-345"><a href="#cb50-345"></a>  <span class="co"># This next line is critical: </span></span>
<span id="cb50-346"><a href="#cb50-346"></a>  <span class="co"># it tells R to maximize rather than minimize</span></span>
<span id="cb50-347"><a href="#cb50-347"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">fnscale =</span> <span class="sc">-</span><span class="dv">1</span>),</span>
<span id="cb50-348"><a href="#cb50-348"></a>  <span class="do">## this is used to calculate standard errors (if you wanted to)</span></span>
<span id="cb50-349"><a href="#cb50-349"></a>  <span class="at">hessian =</span> <span class="cn">TRUE</span> </span>
<span id="cb50-350"><a href="#cb50-350"></a>)</span>
<span id="cb50-351"><a href="#cb50-351"></a></span>
<span id="cb50-352"><a href="#cb50-352"></a><span class="fu">names</span>(opt<span class="sc">$</span>par) <span class="ot">&lt;-</span> <span class="fu">colnames</span>(X)</span>
<span id="cb50-353"><a href="#cb50-353"></a>opt<span class="sc">$</span>par</span>
<span id="cb50-354"><a href="#cb50-354"></a><span class="in">```</span></span>
<span id="cb50-355"><a href="#cb50-355"></a></span>
<span id="cb50-356"><a href="#cb50-356"></a><span class="fu">## Model Comparison</span></span>
<span id="cb50-357"><a href="#cb50-357"></a></span>
<span id="cb50-358"><a href="#cb50-358"></a>We will focus on two measurements that will allow you to adjudicate between models based on their *predictive accuracy.*</span>
<span id="cb50-359"><a href="#cb50-359"></a></span>
<span id="cb50-360"><a href="#cb50-360"></a>Both of them build upon the notion of ***deviance**:*</span>
<span id="cb50-361"><a href="#cb50-361"></a></span>
<span id="cb50-362"><a href="#cb50-362"></a>$$</span>
<span id="cb50-363"><a href="#cb50-363"></a>D = \log(\text{likelihood}) \times -2</span>
<span id="cb50-364"><a href="#cb50-364"></a>$$</span>
<span id="cb50-365"><a href="#cb50-365"></a></span>
<span id="cb50-366"><a href="#cb50-366"></a>**The Akaike Information Criteria**</span>
<span id="cb50-367"><a href="#cb50-367"></a></span>
<span id="cb50-368"><a href="#cb50-368"></a>$$</span>
<span id="cb50-369"><a href="#cb50-369"></a>\text{AIC} = D + k \times 2</span>
<span id="cb50-370"><a href="#cb50-370"></a>$$</span>
<span id="cb50-371"><a href="#cb50-371"></a></span>
<span id="cb50-372"><a href="#cb50-372"></a><span class="kw">&lt;aside&gt;</span>$k$ is the number of parameters in the model<span class="kw">&lt;/aside&gt;</span></span>
<span id="cb50-373"><a href="#cb50-373"></a></span>
<span id="cb50-374"><a href="#cb50-374"></a>**The Bayesian Information Criteria**</span>
<span id="cb50-375"><a href="#cb50-375"></a></span>
<span id="cb50-376"><a href="#cb50-376"></a>$$</span>
<span id="cb50-377"><a href="#cb50-377"></a>\text{BIC} = D + k \times \log(n)</span>
<span id="cb50-378"><a href="#cb50-378"></a>$$</span>
<span id="cb50-379"><a href="#cb50-379"></a></span>
<span id="cb50-380"><a href="#cb50-380"></a>***Out-of-sample deviance***</span>
<span id="cb50-381"><a href="#cb50-381"></a></span>
<span id="cb50-382"><a href="#cb50-382"></a>Steve keeps saying that we *should* really care about how these models perform out-of-sample---i.e., how they are able to describe new observations. We don't want to learn *too much* from our sample; otherwise it will perform poorly on new data *(over-fitting).* We also don't want to learn *too little* from our sample *(under-fitting).*</span>
<span id="cb50-383"><a href="#cb50-383"></a></span>
<span id="cb50-384"><a href="#cb50-384"></a>As it turns out, the AIC approximates the *out-of-sample deviance* of a model.</span>
<span id="cb50-385"><a href="#cb50-385"></a></span>
<span id="cb50-386"><a href="#cb50-386"></a>*The AIC is "asymptotically" equivalent to the so-called leave-one-out cross validation (LOOCV).*</span>
<span id="cb50-387"><a href="#cb50-387"></a></span>
<span id="cb50-388"><a href="#cb50-388"></a>With LOOCV we fit the same model repeatedly to a dataset that excludes one observation and then use the resulting model to calculate the log-likelihood on the observation we left out. Finally, we add up the log-likelihoods and multiply them by $-2$, which means we are actually calculating a *deviance* based on the left-out observations.</span>
<span id="cb50-389"><a href="#cb50-389"></a></span>
<span id="cb50-390"><a href="#cb50-390"></a>The following chunk of code demonstrates this result.</span>
<span id="cb50-391"><a href="#cb50-391"></a></span>
<span id="cb50-394"><a href="#cb50-394"></a><span class="in">```{r}</span></span>
<span id="cb50-395"><a href="#cb50-395"></a><span class="co">#| code-fold: true</span></span>
<span id="cb50-396"><a href="#cb50-396"></a><span class="co">#| code-summary: "Show me"</span></span>
<span id="cb50-397"><a href="#cb50-397"></a><span class="co">#| cache: true</span></span>
<span id="cb50-398"><a href="#cb50-398"></a></span>
<span id="cb50-399"><a href="#cb50-399"></a><span class="do">## we create an empty vessel to store the log-likelihoods for left-out obs</span></span>
<span id="cb50-400"><a href="#cb50-400"></a>out <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"double"</span>, <span class="fu">nrow</span>(d))</span>
<span id="cb50-401"><a href="#cb50-401"></a></span>
<span id="cb50-402"><a href="#cb50-402"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(d)) {</span>
<span id="cb50-403"><a href="#cb50-403"></a>  <span class="do">## note how we exclude the i observation using integer subsetting.</span></span>
<span id="cb50-404"><a href="#cb50-404"></a>  m <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> d[<span class="sc">-</span>i, ])</span>
<span id="cb50-405"><a href="#cb50-405"></a>  <span class="do">## then we get a prediction for the left-out observation</span></span>
<span id="cb50-406"><a href="#cb50-406"></a>  theta <span class="ot">&lt;-</span> <span class="fu">predict</span>(m, <span class="at">newdata =</span> d[i, ], <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb50-407"><a href="#cb50-407"></a>  <span class="do">## then we calculate the log-likelihood for the left-out observation</span></span>
<span id="cb50-408"><a href="#cb50-408"></a>  out[[i]] <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(d<span class="sc">$</span>cappun[[i]], <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> theta, <span class="at">log =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-409"><a href="#cb50-409"></a>}</span>
<span id="cb50-410"><a href="#cb50-410"></a></span>
<span id="cb50-411"><a href="#cb50-411"></a><span class="do">## deviance for the left-out observations</span></span>
<span id="cb50-412"><a href="#cb50-412"></a><span class="fu">sum</span>(out) <span class="sc">*</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb50-413"><a href="#cb50-413"></a><span class="in">```</span></span>
<span id="cb50-414"><a href="#cb50-414"></a></span>
<span id="cb50-415"><a href="#cb50-415"></a>As a reminder, this is the AIC for the model we calculated earlier:</span>
<span id="cb50-416"><a href="#cb50-416"></a></span>
<span id="cb50-419"><a href="#cb50-419"></a><span class="in">```{r}</span></span>
<span id="cb50-420"><a href="#cb50-420"></a><span class="fu">AIC</span>(mod)</span>
<span id="cb50-421"><a href="#cb50-421"></a><span class="in">```</span></span>
<span id="cb50-422"><a href="#cb50-422"></a></span>
<span id="cb50-423"><a href="#cb50-423"></a>*They are almost the same!*</span>
<span id="cb50-424"><a href="#cb50-424"></a></span>
<span id="cb50-425"><a href="#cb50-425"></a>Thus, for most purposes, the AIC provides a good approximation for the out-of-sample deviance.<span class="ot">[^week10-1]</span></span>
<span id="cb50-426"><a href="#cb50-426"></a></span>
<span id="cb50-427"><a href="#cb50-427"></a><span class="ot">[^week10-1]: </span>This will not be the case if the data is structured weirdly---e.g., time-series, nested observations, etc.</span>
<span id="cb50-428"><a href="#cb50-428"></a></span>
<span id="cb50-429"><a href="#cb50-429"></a><span class="fu">## Exercises</span></span>
<span id="cb50-430"><a href="#cb50-430"></a></span>
<span id="cb50-431"><a href="#cb50-431"></a><span class="fu">### Exercise</span></span>
<span id="cb50-432"><a href="#cb50-432"></a></span>
<span id="cb50-433"><a href="#cb50-433"></a>::: callout-note</span>
<span id="cb50-434"><a href="#cb50-434"></a>Describe how the following formulas are reshaping your data frame:</span>
<span id="cb50-435"><a href="#cb50-435"></a></span>
<span id="cb50-436"><a href="#cb50-436"></a><span class="ss">-   </span><span class="in">`cappun ~ polviews + weekly + polviews:weekly`</span></span>
<span id="cb50-437"><a href="#cb50-437"></a></span>
<span id="cb50-438"><a href="#cb50-438"></a><span class="ss">-   </span><span class="in">`cappun ~ polviews * weekly`</span></span>
<span id="cb50-439"><a href="#cb50-439"></a></span>
<span id="cb50-440"><a href="#cb50-440"></a><span class="ss">-   </span><span class="in">`cappun ~ degree`</span></span>
<span id="cb50-441"><a href="#cb50-441"></a></span>
<span id="cb50-442"><a href="#cb50-442"></a>Use the <span class="in">`model.matrix()`</span> function to complement your answers.</span>
<span id="cb50-443"><a href="#cb50-443"></a>:::</span>
<span id="cb50-444"><a href="#cb50-444"></a></span>
<span id="cb50-445"><a href="#cb50-445"></a><span class="fu">### Exercise</span></span>
<span id="cb50-446"><a href="#cb50-446"></a></span>
<span id="cb50-447"><a href="#cb50-447"></a>::: callout-note</span>
<span id="cb50-448"><a href="#cb50-448"></a>*Compare the following models using AIC and BIC.*</span>
<span id="cb50-449"><a href="#cb50-449"></a></span>
<span id="cb50-452"><a href="#cb50-452"></a><span class="in">```{r}</span></span>
<span id="cb50-453"><a href="#cb50-453"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb50-454"><a href="#cb50-454"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">*</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb50-455"><a href="#cb50-455"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> polviews <span class="sc">+</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb50-456"><a href="#cb50-456"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> polviews <span class="sc">*</span> weekly, <span class="at">data =</span> d, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb50-457"><a href="#cb50-457"></a><span class="in">```</span></span>
<span id="cb50-458"><a href="#cb50-458"></a></span>
<span id="cb50-459"><a href="#cb50-459"></a>*Interpret the intercept in all models.*</span>
<span id="cb50-460"><a href="#cb50-460"></a></span>
<span id="cb50-461"><a href="#cb50-461"></a>*Looking at `mod4`, what is the predicted probability that a "slightly conservative" individual that attends religious ceremonies weekly favors capital punishment?*</span>
<span id="cb50-462"><a href="#cb50-462"></a>:::</span>
<span id="cb50-463"><a href="#cb50-463"></a></span>
<span id="cb50-464"><a href="#cb50-464"></a>::: callout-tip</span>
<span id="cb50-465"><a href="#cb50-465"></a>Hint: You can create pretty coefficient tables with the <span class="in">`msummary()`</span> function from the <span class="in">`modelsummary`</span> package.</span>
<span id="cb50-466"><a href="#cb50-466"></a></span>
<span id="cb50-469"><a href="#cb50-469"></a><span class="in">```{r}</span></span>
<span id="cb50-470"><a href="#cb50-470"></a><span class="fu">msummary</span>(<span class="fu">list</span>(mod1, mod2, mod3, mod4), <span class="at">gof_map =</span> <span class="st">"none"</span>)</span>
<span id="cb50-471"><a href="#cb50-471"></a><span class="in">```</span></span>
<span id="cb50-472"><a href="#cb50-472"></a>:::</span>
<span id="cb50-473"><a href="#cb50-473"></a></span>
<span id="cb50-474"><a href="#cb50-474"></a><span class="fu">### Exercise</span></span>
<span id="cb50-475"><a href="#cb50-475"></a></span>
<span id="cb50-476"><a href="#cb50-476"></a>::: callout-note</span>
<span id="cb50-477"><a href="#cb50-477"></a>Transform <span class="in">`polviews`</span> into a new variable that has the following three values:</span>
<span id="cb50-478"><a href="#cb50-478"></a></span>
<span id="cb50-479"><a href="#cb50-479"></a>$$</span>
<span id="cb50-480"><a href="#cb50-480"></a>\texttt{polviews2} = \begin{cases}</span>
<span id="cb50-481"><a href="#cb50-481"></a>\text{liberal} &amp;\text{if} &amp;\text{polviews} &lt; 0 <span class="sc">\\</span></span>
<span id="cb50-482"><a href="#cb50-482"></a>\text{moderate} &amp;\text{if} &amp;\text{polviews} == 0 <span class="sc">\\</span></span>
<span id="cb50-483"><a href="#cb50-483"></a>\text{conservative} &amp;\text{if} &amp;\text{polviews} &gt; 0</span>
<span id="cb50-484"><a href="#cb50-484"></a>\end{cases}</span>
<span id="cb50-485"><a href="#cb50-485"></a>$$</span>
<span id="cb50-486"><a href="#cb50-486"></a></span>
<span id="cb50-487"><a href="#cb50-487"></a>Fit the following model three times, choosing with a new reference category each time.</span>
<span id="cb50-488"><a href="#cb50-488"></a></span>
<span id="cb50-489"><a href="#cb50-489"></a><span class="ss">-   </span><span class="in">`cappun ~ polviews2 + weekly`</span></span>
<span id="cb50-490"><a href="#cb50-490"></a></span>
<span id="cb50-491"><a href="#cb50-491"></a>Interpret the coefficients.</span>
<span id="cb50-492"><a href="#cb50-492"></a>:::</span>
<span id="cb50-493"><a href="#cb50-493"></a></span>
<span id="cb50-494"><a href="#cb50-494"></a>::: callout-tip</span>
<span id="cb50-495"><a href="#cb50-495"></a>Hint: You can create this variable by using two nested <span class="in">`if_else()`</span> statements, but you might want to prefer using the <span class="in">`case_when()`</span> function.</span>
<span id="cb50-496"><a href="#cb50-496"></a></span>
<span id="cb50-497"><a href="#cb50-497"></a><span class="ot">&lt;https://dplyr.tidyverse.org/reference/case_when.html&gt;</span></span>
<span id="cb50-498"><a href="#cb50-498"></a>:::</span>
<span id="cb50-499"><a href="#cb50-499"></a></span>
<span id="cb50-500"><a href="#cb50-500"></a>::: callout-tip</span>
<span id="cb50-501"><a href="#cb50-501"></a>Hint: You can change the reference category using the <span class="in">`fct_relevel()`</span></span>
<span id="cb50-502"><a href="#cb50-502"></a></span>
<span id="cb50-503"><a href="#cb50-503"></a><span class="ot">&lt;https://forcats.tidyverse.org/reference/fct_relevel.html&gt;</span></span>
<span id="cb50-504"><a href="#cb50-504"></a>:::</span>
<span id="cb50-505"><a href="#cb50-505"></a></span>
<span id="cb50-506"><a href="#cb50-506"></a><span class="fu">### Exercise</span></span>
<span id="cb50-507"><a href="#cb50-507"></a></span>
<span id="cb50-508"><a href="#cb50-508"></a>::: callout-note</span>
<span id="cb50-509"><a href="#cb50-509"></a>Fill in the conditional probabilities in the following table:</span>
<span id="cb50-510"><a href="#cb50-510"></a></span>
<span id="cb50-511"><a href="#cb50-511"></a>| <span class="in">`weekly`</span> | <span class="in">`polviews2`</span>  | Saturated Model | Restricted Model |</span>
<span id="cb50-512"><a href="#cb50-512"></a>|----------|--------------|-----------------|------------------|</span>
<span id="cb50-513"><a href="#cb50-513"></a>| 0        | liberal      |                 |                  |</span>
<span id="cb50-514"><a href="#cb50-514"></a>| 0        | moderate     |                 |                  |</span>
<span id="cb50-515"><a href="#cb50-515"></a>| 0        | conservative |                 |                  |</span>
<span id="cb50-516"><a href="#cb50-516"></a>| 1        | liberal      |                 |                  |</span>
<span id="cb50-517"><a href="#cb50-517"></a>| 1        | moderate     |                 |                  |</span>
<span id="cb50-518"><a href="#cb50-518"></a>| 1        | conservative |                 |                  |</span>
<span id="cb50-519"><a href="#cb50-519"></a></span>
<span id="cb50-520"><a href="#cb50-520"></a>: Probability that a respondent favors capital punishment ( $\texttt{cappun} = 1$ )</span>
<span id="cb50-521"><a href="#cb50-521"></a>:::</span>
<span id="cb50-522"><a href="#cb50-522"></a></span>
<span id="cb50-523"><a href="#cb50-523"></a>::: callout-tip</span>
<span id="cb50-524"><a href="#cb50-524"></a>Hint: There are two ways to estimate the "saturated model".</span>
<span id="cb50-525"><a href="#cb50-525"></a></span>
<span id="cb50-526"><a href="#cb50-526"></a><span class="ss">-   </span>Using the model formula that includes all interactions: <span class="in">`cappun ~ weekly*polviews2`</span>.</span>
<span id="cb50-527"><a href="#cb50-527"></a></span>
<span id="cb50-528"><a href="#cb50-528"></a>    Then you can use either <span class="in">`predict()`</span> or <span class="in">`broom::augment()`</span></span>
<span id="cb50-529"><a href="#cb50-529"></a></span>
<span id="cb50-530"><a href="#cb50-530"></a><span class="ss">-   </span>Using <span class="in">`dplyr`</span></span>
<span id="cb50-531"><a href="#cb50-531"></a></span>
<span id="cb50-532"><a href="#cb50-532"></a>    <span class="in">```{r}</span></span>
<span id="cb50-533"><a href="#cb50-533"></a>    <span class="co">#| eval: false</span></span>
<span id="cb50-534"><a href="#cb50-534"></a>    d <span class="sc">|&gt;</span> </span>
<span id="cb50-535"><a href="#cb50-535"></a>      <span class="fu">group_by</span>(weekly, polviews2) <span class="sc">|&gt;</span> </span>
<span id="cb50-536"><a href="#cb50-536"></a>      <span class="fu">summarize</span>(<span class="at">p =</span> <span class="fu">mean</span>(cappun))</span>
<span id="cb50-537"><a href="#cb50-537"></a>    <span class="in">```</span></span>
<span id="cb50-538"><a href="#cb50-538"></a>:::</span>
<span id="cb50-539"><a href="#cb50-539"></a></span>
<span id="cb50-540"><a href="#cb50-540"></a><span class="fu">### Exercise</span></span>
<span id="cb50-541"><a href="#cb50-541"></a></span>
<span id="cb50-542"><a href="#cb50-542"></a>::: callout-note</span>
<span id="cb50-543"><a href="#cb50-543"></a>Do the following:</span>
<span id="cb50-544"><a href="#cb50-544"></a></span>
<span id="cb50-545"><a href="#cb50-545"></a><span class="ss">-   </span>Look at the GSS data and choose an outcome variable that interests you.</span>
<span id="cb50-546"><a href="#cb50-546"></a></span>
<span id="cb50-547"><a href="#cb50-547"></a><span class="ss">-   </span>Choose 2 or 3 predictors that interests you.</span>
<span id="cb50-548"><a href="#cb50-548"></a></span>
<span id="cb50-549"><a href="#cb50-549"></a><span class="ss">-   </span>Create at least two models and then compare them using AIC and BIC.</span>
<span id="cb50-550"><a href="#cb50-550"></a></span>
<span id="cb50-551"><a href="#cb50-551"></a>    Which model has a better out-of-sample predictive accuracy?</span>
<span id="cb50-552"><a href="#cb50-552"></a></span>
<span id="cb50-553"><a href="#cb50-553"></a><span class="ss">-   </span>What is the relationship between your outcome and your predictors?</span>
<span id="cb50-554"><a href="#cb50-554"></a></span>
<span id="cb50-555"><a href="#cb50-555"></a>    *Don't worry about making causal claims unless you think they are reasonable.*</span>
<span id="cb50-556"><a href="#cb50-556"></a></span>
<span id="cb50-557"><a href="#cb50-557"></a><span class="ss">-   </span>*Keep it simple! This is only a class exercise!*</span>
<span id="cb50-558"><a href="#cb50-558"></a>:::</span>
<span id="cb50-559"><a href="#cb50-559"></a></span>
<span id="cb50-560"><a href="#cb50-560"></a><span class="fu">### Extra</span></span>
<span id="cb50-561"><a href="#cb50-561"></a></span>
<span id="cb50-562"><a href="#cb50-562"></a>I was originally going to ask you to calculate the standard deviations for bootstrap sampling distributions corresponding to $\alpha$, $\beta_1$, and $\beta_2$ in @eq-restricted. The plan was to show you that these values correspond to the "standard errors" shown in the regression output.</span>
<span id="cb50-563"><a href="#cb50-563"></a></span>
<span id="cb50-564"><a href="#cb50-564"></a>Unfortunately, I couldn't find a way to do this easily with the <span class="in">`infer`</span> package, so here's the code to do it:</span>
<span id="cb50-565"><a href="#cb50-565"></a></span>
<span id="cb50-568"><a href="#cb50-568"></a><span class="in">```{r}</span></span>
<span id="cb50-569"><a href="#cb50-569"></a><span class="co">#| cache: true</span></span>
<span id="cb50-570"><a href="#cb50-570"></a>boot_coef <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="at">n =</span> <span class="fl">2e3</span>, <span class="at">simplify =</span> <span class="cn">FALSE</span>, <span class="at">expr =</span> {</span>
<span id="cb50-571"><a href="#cb50-571"></a>  i <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(d), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-572"><a href="#cb50-572"></a>  m <span class="ot">&lt;-</span> <span class="fu">glm</span>(cappun <span class="sc">~</span> conservative <span class="sc">+</span> weekly, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> d[i, ])</span>
<span id="cb50-573"><a href="#cb50-573"></a>  <span class="fu">coefficients</span>(m)</span>
<span id="cb50-574"><a href="#cb50-574"></a>}) <span class="sc">|&gt;</span> <span class="fu">bind_rows</span>()</span>
<span id="cb50-575"><a href="#cb50-575"></a></span>
<span id="cb50-576"><a href="#cb50-576"></a><span class="fu">glimpse</span>(boot_coef)</span>
<span id="cb50-577"><a href="#cb50-577"></a></span>
<span id="cb50-578"><a href="#cb50-578"></a>boot_coef <span class="sc">|&gt;</span> </span>
<span id="cb50-579"><a href="#cb50-579"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"term"</span>, <span class="at">values_to =</span> <span class="st">"stat"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb50-580"><a href="#cb50-580"></a>  <span class="fu">group_by</span>(term) <span class="sc">|&gt;</span> </span>
<span id="cb50-581"><a href="#cb50-581"></a>  <span class="fu">summarize</span>(<span class="at">estimate =</span> <span class="fu">mean</span>(stat), <span class="at">std.error =</span> <span class="fu">sd</span>(stat))</span>
<span id="cb50-582"><a href="#cb50-582"></a></span>
<span id="cb50-583"><a href="#cb50-583"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(mod)</span>
<span id="cb50-584"><a href="#cb50-584"></a><span class="in">```</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>